Emotions integration
child-lab-uj/child-lab-framework pull request #51
Opened 2024-11-06 23:42 UTC by WojciechBarczynski

2024-11-06 23:51 UTC, integraledelebesgue submitted a review, later dismissed

2024-11-06 23:51 UTC, integraledelebesgue commented on child_lab_framework/task/emotions/emotions.py
I would name this module `emotion` to keep task names consistent.

2024-11-06 23:51 UTC, integraledelebesgue commented on child_lab_framework/task/emotions/emotions.py
> +def score_emotions(emotions):
Please add typing :)

2024-11-07 00:00 UTC, integraledelebesgue requested changes

2024-11-07 00:00 UTC, integraledelebesgue commented on child_lab_framework/task/emotion/emotion.py
> +        for face_box in faces.boxes:
`faces.boxes` reference is not safe since `faces` can be `None`. This function should return `Result | None` and perform a check on `faces`

2024-11-07 00:00 UTC, integraledelebesgue commented on child_lab_framework/task/emotion/emotion.py
> +    boxes: list[FloatArray2]
We could stack these results and stored as `np.ndarray`s instead of lists. We do so in other `Result`s in general

2024-11-07 00:01 UTC, integraledelebesgue commented on child_lab_framework/task/emotion/emotion.py
> +def score_emotions(emotions: List[Dict[str, float]]) -> float:
```suggestion
def score_emotions(emotions: list[dict[str, float]]) -> float:
```
`List` etc. are deprecated

2024-11-07 00:02 UTC, integraledelebesgue commented on child_lab_framework/task/emotion/emotion.py
> +from typing import Dict, List
```suggestion
```

2024-11-07 00:07 UTC, integraledelebesgue commented on child_lab_framework/task/emotion/emotion.py
> +        for face_box in faces.boxes:
Btw, `predict` method should take not-none arguments. You can rename this method to `__predict_safe` and use it in `stream`, `predict_batch` and a proper `predict`.

2024-11-07 00:08 UTC, integraledelebesgue commented on child_lab_framework/task/emotion/emotion.py
> +]
This type is obsolete if you don't use it in `stream`

2024-11-07 00:26 UTC, integraledelebesgue commented on child_lab_framework/task/emotion/emotion.py
> +        self.boxes = boxes
This should be a frozen dataclass

2024-11-07 00:26 UTC, integraledelebesgue commented on child_lab_framework/task/emotion/emotion.py
> +def score_emotions(emotions: List[Dict[str, float]]) -> float:
```suggestion
def __score(emotions: List[Dict[str, float]]) -> float:
```
No need to duplicate information; should be private too

2024-11-07 00:26 UTC, integraledelebesgue commented on child_lab_framework/task/emotion/emotion.py
> +    }
This dict shouldn't be located here since it is going to be created on each call 💀 Please make it a private constant

2024-11-07 00:26 UTC, integraledelebesgue commented on child_lab_framework/task/emotion/emotion.py
> +                                self.__predict,
This method doesn't even exist 🙉 I guess this was meant to be `__predict_safe` which I mentioned [here](https://github.com/child-lab-uj/child-lab-framework/pull/51/files#r1831877464)

2024-11-07 00:26 UTC, integraledelebesgue commented on child_lab_framework/task/emotion/emotion.py
> +from child_lab_framework.task import face
Please make these imports relative

2024-11-07 00:26 UTC, integraledelebesgue commented on child_lab_framework/task/emotion/emotion.py
> +    boxes: list[FloatArray2]
Also, it's no use duplicating `face.Result` as `boxes` here

2024-11-07 23:29 UTC, integraledelebesgue commented on child_lab_framework/task/emotion/emotion.py
> +def score_emotions(emotions: List[Dict[str, float]]) -> float:
Update: you cannot actually call `__<free-function-name>` inside class because that dumb Python assumes that you're calling a static method 🙄 Please make this a static method then

2024-11-07 23:32 UTC, integraledelebesgue commented on child_lab_framework/task/emotion/emotion.py
> +    }
With [this](https://github.com/child-lab-uj/child-lab-framework/pull/51#discussion_r1833501975) in mind - please make this dict injected into an `Estimator` via constructor.

2024-11-14 08:09 UTC, WojciechBarczynski commented on child_lab_framework/task/emotion/emotion.py
> +    boxes: list[FloatArray2]
There is - that way there is no coupling between emotion recognition and face detection in the visualization layer.

Duplicating it is almost free (the cost of doing that is negligible), but it's much easier to handle it that way in the visualization layer.

2025-03-16 21:46 UTC, closed without merging